version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tempPassword
      POSTGRES_DB: basic_spring_boot_api_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: production
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/basic_spring_boot_api_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tempPassword
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: react-app
    ports:
      - "5173:5173"
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  pgdata:
