version: '3.8'

services:
  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tempPassword
      POSTGRES_DB: basic_spring_boot_api_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
